src/Entity/Camping.php
<?php

namespace App\Entity;

use App\Repository\CampingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CampingRepository::class)
 */
class Camping
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_camp;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut_camp;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin_camp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_camp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $descri_camp;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbre_place_camp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_camp;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_camp;

    /**
     * @ORM\OneToMany(targetEntity=Reservationcamp::class, mappedBy="camping")
     */
    private $reservation;

    public function __construct()
    {
        $this->reservation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCamp(): ?string
    {
        return $this->nom_camp;
    }

    public function setNomCamp(string $nom_camp): self
    {
        $this->nom_camp = $nom_camp;

        return $this;
    }

    public function getDateDebutCamp(): ?\DateTimeInterface
    {
        return $this->date_debut_camp;
    }

    public function setDateDebutCamp(\DateTimeInterface $date_debut_camp): self
    {
        $this->date_debut_camp = $date_debut_camp;

        return $this;
    }

    public function getDateFinCamp(): ?\DateTimeInterface
    {
        return $this->date_fin_camp;
    }

    public function setDateFinCamp(\DateTimeInterface $date_fin_camp): self
    {
        $this->date_fin_camp = $date_fin_camp;

        return $this;
    }

    public function getLieuCamp(): ?string
    {
        return $this->lieu_camp;
    }

    public function setLieuCamp(string $lieu_camp): self
    {
        $this->lieu_camp = $lieu_camp;

        return $this;
    }

    public function getDescriCamp(): ?string
    {
        return $this->descri_camp;
    }

    public function setDescriCamp(string $descri_camp): self
    {
        $this->descri_camp = $descri_camp;

        return $this;
    }

    public function getNbrePlaceCamp(): ?int
    {
        return $this->nbre_place_camp;
    }

    public function setNbrePlaceCamp(int $nbre_place_camp): self
    {
        $this->nbre_place_camp = $nbre_place_camp;

        return $this;
    }

    public function getImageCamp(): ?string
    {
        return $this->image_camp;
    }

    public function setImageCamp(string $image_camp): self
    {
        $this->image_camp = $image_camp;

        return $this;
    }

    public function getPrixCamp(): ?float
    {
        return $this->prix_camp;
    }

    public function setPrixCamp(float $prix_camp): self
    {
        $this->prix_camp = $prix_camp;

        return $this;
    }

    /**
     * @return Collection|Reservationcamp[]
     */
    public function getReservation(): Collection
    {
        return $this->reservation;
    }

    public function addReservation(Reservationcamp $reservation): self
    {
        if (!$this->reservation->contains($reservation)) {
            $this->reservation[] = $reservation;
            $reservation->setCamping($this);
        }

        return $this;
    }

    public function removeReservation(Reservationcamp $reservation): self
    {
        if ($this->reservation->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCamping() === $this) {
                $reservation->setCamping(null);
            }
        }

        return $this;
    }
}

src/Form/CampingType.php
<?php

namespace App\Form;

use App\Entity\Camping;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_camp')
            ->add('date_debut_camp')
            ->add('date_fin_camp')
            ->add('lieu_camp')
            ->add('descri_camp')
            ->add('nbre_place_camp')
            ->add('image_camp')
            ->add('prix_camp')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Camping::class,
        ]);
    }
}

src/Controller/CampingController.php
<?php

namespace App\Controller;

use App\Entity\Camping;
use App\Form\CampingType;
use App\Repository\CampingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/camping")
 */
class CampingController extends AbstractController
{
    /**
     * @Route("/", name="camping_index", methods={"GET"})
     */
    public function index(CampingRepository $campingRepository): Response
    {
        return $this->render('camping/index.html.twig', [
            'campings' => $campingRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="camping_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $camping = new Camping();
        $form = $this->createForm(CampingType::class, $camping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($camping);
            $entityManager->flush();

            return $this->redirectToRoute('camping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('camping/new.html.twig', [
            'camping' => $camping,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="camping_show", methods={"GET"})
     */
    public function show(Camping $camping): Response
    {
        return $this->render('camping/show.html.twig', [
            'camping' => $camping,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="camping_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Camping $camping): Response
    {
        $form = $this->createForm(CampingType::class, $camping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('camping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('camping/edit.html.twig', [
            'camping' => $camping,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="camping_delete", methods={"POST"})
     */
    public function delete(Request $request, Camping $camping): Response
    {
        if ($this->isCsrfTokenValid('delete'.$camping->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($camping);
            $entityManager->flush();
        }

        return $this->redirectToRoute('camping_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/camping/_delete_form.html.twig
<form method="post" action="{{ path('camping_delete', {'id': camping.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ camping.id) }}">
    <button class="btn">Delete</button>
</form>

templates/camping/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/camping/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Camping{% endblock %}

{% block body %}
    <h1>Edit Camping</h1>

    {{ include('camping/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('camping_index') }}">back to list</a>

    {{ include('camping/_delete_form.html.twig') }}
{% endblock %}

templates/camping/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Camping index{% endblock %}

{% block body %}
    <h1>Camping index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_camp</th>
                <th>Date_debut_camp</th>
                <th>Date_fin_camp</th>
                <th>Lieu_camp</th>
                <th>Descri_camp</th>
                <th>Nbre_place_camp</th>
                <th>Image_camp</th>
                <th>Prix_camp</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for camping in campings %}
            <tr>
                <td>{{ camping.id }}</td>
                <td>{{ camping.nomCamp }}</td>
                <td>{{ camping.dateDebutCamp ? camping.dateDebutCamp|date('Y-m-d') : '' }}</td>
                <td>{{ camping.dateFinCamp ? camping.dateFinCamp|date('Y-m-d') : '' }}</td>
                <td>{{ camping.lieuCamp }}</td>
                <td>{{ camping.descriCamp }}</td>
                <td>{{ camping.nbrePlaceCamp }}</td>
                <td>{{ camping.imageCamp }}</td>
                <td>{{ camping.prixCamp }}</td>
                <td>
                    <a href="{{ path('camping_show', {'id': camping.id}) }}">show</a>
                    <a href="{{ path('camping_edit', {'id': camping.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('camping_new') }}">Create new</a>
{% endblock %}

templates/camping/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Camping{% endblock %}

{% block body %}
    <h1>Create new Camping</h1>

    {{ include('camping/_form.html.twig') }}

    <a href="{{ path('camping_index') }}">back to list</a>
{% endblock %}

templates/camping/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Camping{% endblock %}

{% block body %}
    <h1>Camping</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ camping.id }}</td>
            </tr>
            <tr>
                <th>Nom_camp</th>
                <td>{{ camping.nomCamp }}</td>
            </tr>
            <tr>
                <th>Date_debut_camp</th>
                <td>{{ camping.dateDebutCamp ? camping.dateDebutCamp|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin_camp</th>
                <td>{{ camping.dateFinCamp ? camping.dateFinCamp|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Lieu_camp</th>
                <td>{{ camping.lieuCamp }}</td>
            </tr>
            <tr>
                <th>Descri_camp</th>
                <td>{{ camping.descriCamp }}</td>
            </tr>
            <tr>
                <th>Nbre_place_camp</th>
                <td>{{ camping.nbrePlaceCamp }}</td>
            </tr>
            <tr>
                <th>Image_camp</th>
                <td>{{ camping.imageCamp }}</td>
            </tr>
            <tr>
                <th>Prix_camp</th>
                <td>{{ camping.prixCamp }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('camping_index') }}">back to list</a>

    <a href="{{ path('camping_edit', {'id': camping.id}) }}">edit</a>

    {{ include('camping/_delete_form.html.twig') }}
{% endblock %}