src/Entity/CarteFidelite.php
<?php

namespace App\Entity;

use App\Repository\CarteFideliteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CarteFideliteRepository::class)
 */
class CarteFidelite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_fid;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut_fid;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin_fid;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumFid(): ?int
    {
        return $this->num_fid;
    }

    public function setNumFid(int $num_fid): self
    {
        $this->num_fid = $num_fid;

        return $this;
    }

    public function getDateDebutFid(): ?\DateTimeInterface
    {
        return $this->date_debut_fid;
    }

    public function setDateDebutFid(\DateTimeInterface $date_debut_fid): self
    {
        $this->date_debut_fid = $date_debut_fid;

        return $this;
    }

    public function getDateFinFid(): ?\DateTimeInterface
    {
        return $this->date_fin_fid;
    }

    public function setDateFinFid(\DateTimeInterface $date_fin_fid): self
    {
        $this->date_fin_fid = $date_fin_fid;

        return $this;
    }
    public function __toString() {
        return $this->num_fid;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 */
class Utilisateur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mot_passe_utili;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_utili;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tel_utili;

    /**
     * @ORM\Column(type="integer")
     */
    private $role;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_place;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message = ".")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToOne(targetEntity=CarteFidelite::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $carteFid;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotPasseUtili(): ?string
    {
        return $this->mot_passe_utili;
    }

    public function setMotPasseUtili(?string $mot_passe_utili): self
    {
        $this->mot_passe_utili = $mot_passe_utili;

        return $this;
    }

    public function getNomUtili(): ?string
    {
        return $this->nom_utili;
    }

    public function setNomUtili(?string $nom_utili): self
    {
        $this->nom_utili = $nom_utili;

        return $this;
    }

    public function getTelUtili(): ?int
    {
        return $this->tel_utili;
    }

    public function setTelUtili(?int $tel_utili): self
    {
        $this->tel_utili = $tel_utili;

        return $this;
    }

    public function getRole(): ?int
    {
        return $this->role;
    }

    public function setRole(int $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNbrePlace(): ?int
    {
        return $this->nbre_place;
    }

    public function setNbrePlace(?int $nbre_place): self
    {
        $this->nbre_place = $nbre_place;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCarteFid(): ?CarteFidelite
    {
        return $this->carteFid;
    }

    public function setCarteFid(CarteFidelite $carteFid): self
    {
        $this->carteFid = $carteFid;

        return $this;
    }



}

src/Controller/CarteFideliteController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\UtilisateurType;
use App\Repository\UtilisateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/carte/fidelite")
 */
class CarteFideliteController extends AbstractController
{
    /**
     * @Route("/", name="carte_fidelite_index", methods={"GET"})
     */
    public function index(UtilisateurRepository $utilisateurRepository): Response
    {
        return $this->render('carte_fidelite/index.html.twig', [
            'utilisateurs' => $utilisateurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="carte_fidelite_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $utilisateur = new Utilisateur();
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($utilisateur);
            $entityManager->flush();

            return $this->redirectToRoute('carte_fidelite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('carte_fidelite/new.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="carte_fidelite_show", methods={"GET"})
     */
    public function show(Utilisateur $utilisateur): Response
    {
        return $this->render('carte_fidelite/show.html.twig', [
            'utilisateur' => $utilisateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="carte_fidelite_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Utilisateur $utilisateur): Response
    {
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('carte_fidelite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('carte_fidelite/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="carte_fidelite_delete", methods={"POST"})
     */
    public function delete(Request $request, Utilisateur $utilisateur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$utilisateur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($utilisateur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('carte_fidelite_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/carte_fidelite/_delete_form.html.twig
<form method="post" action="{{ path('carte_fidelite_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/carte_fidelite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/carte_fidelite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Utilisateur{% endblock %}

{% block body %}
    <h1>Edit Utilisateur</h1>

    {{ include('carte_fidelite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('carte_fidelite_index') }}">back to list</a>

    {{ include('carte_fidelite/_delete_form.html.twig') }}
{% endblock %}

templates/carte_fidelite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur index{% endblock %}

{% block body %}
    <h1>Utilisateur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Mot_passe_utili</th>
                <th>Nom_utili</th>
                <th>Tel_utili</th>
                <th>Role</th>
                <th>Type</th>
                <th>Nbre_place</th>
                <th>Email</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for utilisateur in utilisateurs %}
            <tr>
                <td>{{ utilisateur.id }}</td>
                <td>{{ utilisateur.motPasseUtili }}</td>
                <td>{{ utilisateur.nomUtili }}</td>
                <td>{{ utilisateur.telUtili }}</td>
                <td>{{ utilisateur.role }}</td>
                <td>{{ utilisateur.type }}</td>
                <td>{{ utilisateur.nbrePlace }}</td>
                <td>{{ utilisateur.email }}</td>
                <td>{{ utilisateur.image }}</td>
                <td>
                    <a href="{{ path('carte_fidelite_show', {'id': utilisateur.id}) }}">show</a>
                    <a href="{{ path('carte_fidelite_edit', {'id': utilisateur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('carte_fidelite_new') }}">Create new</a>
{% endblock %}

templates/carte_fidelite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Utilisateur{% endblock %}

{% block body %}
    <h1>Create new Utilisateur</h1>

    {{ include('carte_fidelite/_form.html.twig') }}

    <a href="{{ path('carte_fidelite_index') }}">back to list</a>
{% endblock %}

templates/carte_fidelite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <h1>Utilisateur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ utilisateur.id }}</td>
            </tr>
            <tr>
                <th>Mot_passe_utili</th>
                <td>{{ utilisateur.motPasseUtili }}</td>
            </tr>
            <tr>
                <th>Nom_utili</th>
                <td>{{ utilisateur.nomUtili }}</td>
            </tr>
            <tr>
                <th>Tel_utili</th>
                <td>{{ utilisateur.telUtili }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ utilisateur.role }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ utilisateur.type }}</td>
            </tr>
            <tr>
                <th>Nbre_place</th>
                <td>{{ utilisateur.nbrePlace }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ utilisateur.email }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ utilisateur.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('carte_fidelite_index') }}">back to list</a>

    <a href="{{ path('carte_fidelite_edit', {'id': utilisateur.id}) }}">edit</a>

    {{ include('carte_fidelite/_delete_form.html.twig') }}
{% endblock %}